"use strict";
//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var exception_ttypes = require('./exception_types')


var ttypes = require('./sku_types');
//HELPER FUNCTIONS AND STRUCTURES

var SkuRPC_get_sku_list_args = function(args) {
};
SkuRPC_get_sku_list_args.prototype = {};
SkuRPC_get_sku_list_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_list_args.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_list_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPC_get_sku_list_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
SkuRPC_get_sku_list_result.prototype = {};
SkuRPC_get_sku_list_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.success = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.SkuList();
          elem6.read(input);
          this.success.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_list_result.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_list_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter7 in this.success)
    {
      if (this.success.hasOwnProperty(iter7))
      {
        iter7 = this.success[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPC_get_sku_pics_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
  }
};
SkuRPC_get_sku_pics_args.prototype = {};
SkuRPC_get_sku_pics_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_pics_args.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_pics_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPC_get_sku_pics_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
SkuRPC_get_sku_pics_result.prototype = {};
SkuRPC_get_sku_pics_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.success = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = new ttypes.SkuPicList();
          elem14.read(input);
          this.success.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_pics_result.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_pics_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter15 in this.success)
    {
      if (this.success.hasOwnProperty(iter15))
      {
        iter15 = this.success[iter15];
        iter15.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPC_get_sku_detail_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined) {
      this.id = args.id;
    }
  }
};
SkuRPC_get_sku_detail_args.prototype = {};
SkuRPC_get_sku_detail_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_detail_args.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_detail_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPC_get_sku_detail_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
SkuRPC_get_sku_detail_result.prototype = {};
SkuRPC_get_sku_detail_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.SkuDetail();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

SkuRPC_get_sku_detail_result.prototype.write = function(output) {
  output.writeStructBegin('SkuRPC_get_sku_detail_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var SkuRPCClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
SkuRPCClient.prototype = {};
SkuRPCClient.prototype.get_sku_list = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_sku_list();
};

SkuRPCClient.prototype.send_get_sku_list = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_sku_list', Thrift.MessageType.CALL, this.seqid);
  var args = new SkuRPC_get_sku_list_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SkuRPCClient.prototype.recv_get_sku_list = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SkuRPC_get_sku_list_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_sku_list failed: unknown result');
};
SkuRPCClient.prototype.get_sku_pics = function(id, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_sku_pics(id);
};

SkuRPCClient.prototype.send_get_sku_pics = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_sku_pics', Thrift.MessageType.CALL, this.seqid);
  var args = new SkuRPC_get_sku_pics_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SkuRPCClient.prototype.recv_get_sku_pics = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SkuRPC_get_sku_pics_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_sku_pics failed: unknown result');
};
SkuRPCClient.prototype.get_sku_detail = function(id, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_get_sku_detail(id);
};

SkuRPCClient.prototype.send_get_sku_detail = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('get_sku_detail', Thrift.MessageType.CALL, this.seqid);
  var args = new SkuRPC_get_sku_detail_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

SkuRPCClient.prototype.recv_get_sku_detail = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new SkuRPC_get_sku_detail_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('get_sku_detail failed: unknown result');
};
var SkuRPCProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
SkuRPCProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

SkuRPCProcessor.prototype.process_get_sku_list = function(seqid, input, output) {
  var args = new SkuRPC_get_sku_list_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_sku_list(function (err, result) {
    var result = new SkuRPC_get_sku_list_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_sku_list", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

SkuRPCProcessor.prototype.process_get_sku_pics = function(seqid, input, output) {
  var args = new SkuRPC_get_sku_pics_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_sku_pics(args.id, function (err, result) {
    var result = new SkuRPC_get_sku_pics_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_sku_pics", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

SkuRPCProcessor.prototype.process_get_sku_detail = function(seqid, input, output) {
  var args = new SkuRPC_get_sku_detail_args();
  args.read(input);
  input.readMessageEnd();
  this._handler.get_sku_detail(args.id, function (err, result) {
    var result = new SkuRPC_get_sku_detail_result((err != null ? err : {success: result}));
    output.writeMessageBegin("get_sku_detail", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

